% test the model with a grid search

clear all;

path = fileparts( which('code/analyseLassoModel.m') );
path = [path '/../results/'];

setup.model.class = @JumpModel;
setup.model.args.ModelType = 'Linear';
setup.model.args.ContinuousEncodingArgs.AlignmentMethod = 'LMTakeoffPeak';
setup.model.args.ContinuousEncodingArgs.NumComponents = 23;
setup.model.args.Optimize = true;
setup.model.args.CompressModel = true;

setup.eval.CVType = 'KFold';
setup.eval.KFolds = 2;
setup.eval.KFoldRepeats = 5;
setup.eval.RandomSeed = 1234;
setup.eval.InParallel = false;

parameters = [ "model.args.EncodingType", ...
               "model.args.NumPredictors", ...
               "data.class", ...
               "model.args.ModelType" ];
values = {{'Discrete', 'Continuous', 'Combined'}, ...
          3:2:23, ...
          {@SmartphoneDataset, @AccelerometerDataset}, ....
          {'Linear', 'Lasso', 'SVM', 'XGBoost'}};

myInvestigation = ParallelInvestigation( 'Predictors', path, parameters, values, setup );

myInvestigation.run;
report = myInvestigation.saveReport;

%% plot RMSE as a function of the number of predictors

figTrn = plotModelPerformance( report, ...
                              'Number of Features', ...
                              'StdRMSE', 'Standardised RMSE', ...
                              Set = 'Training', ...
                              XLimits = [0 25], ...
                              YLimits = [0.1 1], ...
                              YTickInterval = 0.5, ...
                              YLogScale = true, ...
                              FitType = 'gpr',...
                              GPBasisFunction = 'none', ...
                              GPKernelFunction = 'matern52');

figVal = plotModelPerformance( report, ...
                              'Number of Features', ...
                              'StdRMSE', 'Standardised RMSE', ...
                              Set = 'Validation', ...
                              XLimits = [0 25], ...
                              YLimits = [0.4 1.5], ...
                              YTickInterval = 0.5, ...
                              YLogScale = true, ...
                              FitType = 'gpr',...
                              GPBasisFunction = 'none', ...
                              GPKernelFunction = 'matern52');

saveGraphicsObject( figTrn, path, 'ModelTypeTraining' );
saveGraphicsObject( figVal, path, 'ModelTypeValidation' );